"""Short browser-compatible fragments generated only near the requested playhead."""
from __future__ import annotations

import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import threading
import time
from functools import lru_cache
from pathlib import Path

VERSION = "preview-fragments-v1"
CHUNK_SECONDS = 4.0
CACHE_LIMIT = 1024 ** 3
_LOCKS = [threading.Lock() for _ in range(64)]
_CLEANUP_LOCK = threading.Lock()
_last_cleanup = 0.0
_GPU_LOCK = threading.Lock()
_HARDWARE_DISABLED = set()


@lru_cache(maxsize=1)
def hardware_decoders():
    """Inspect this host, never requiring a particular GPU or GPU runtime."""
    ffmpeg = shutil.which("ffmpeg")
    if not ffmpeg:
        return ()
    try:
        accelerators = subprocess.run([ffmpeg, "-hide_banner", "-hwaccels"],
                                     capture_output=True, text=True, timeout=5)
        filters = subprocess.run([ffmpeg, "-hide_banner", "-filters"],
                                 capture_output=True, text=True, timeout=5)
        if accelerators.returncode or filters.returncode:
            return ()
    except (OSError, subprocess.TimeoutExpired):
        return ()
    available = set(accelerators.stdout.split())
    candidates = []
    smi = shutil.which("nvidia-smi")
    if "cuda" in available and smi:
        try:
            devices = subprocess.run([smi, "--query-gpu=index", "--format=csv,noheader"],
                                     capture_output=True, text=True, timeout=5)
            if devices.returncode == 0:
                candidates.extend(("cuda", index.strip(), "scale_cuda" in filters.stdout)
                                  for index in devices.stdout.splitlines() if index.strip().isdigit())
        except (OSError, subprocess.TimeoutExpired):
            pass
    if sys.platform.startswith("linux") and "vaapi" in available:
        # VAAPI covers supported Intel and AMD Linux drivers. Try accessible
        # devices individually; a codec can work on one GPU but not another.
        candidates.extend(("vaapi", str(device), "scale_vaapi" in filters.stdout)
                          for device in sorted(Path("/dev/dri").glob("renderD*"))
                          if os.access(device, os.R_OK | os.W_OK))
    if sys.platform == "win32" and "d3d11va" in available:
        # The default Direct3D 11 adapter works across GPU vendors. A compiled
        # FFmpeg backend alone does not guarantee a working driver: encoding
        # failures below fall back to CPU and suppress repeated failed tries.
        candidates.append(("d3d11va", None, False))
    if sys.platform == "darwin" and "videotoolbox" in available:
        candidates.append(("videotoolbox", None, False))
    # A driver may decode a codec successfully but lack GPU scaling support.
    # Retain a decode-only attempt before falling back entirely to CPU.
    return tuple(option for method, device, scaling in candidates
                 for option in (((method, device, True), (method, device, False))
                                if scaling else ((method, device, False),)))


def source_key(path, acceleration="auto"):
    if acceleration not in {"auto", "cpu"}:
        raise ValueError("Preview acceleration must be Auto or CPU")
    path = Path(path)
    stat = path.stat()
    key = [VERSION, str(path.resolve()), stat.st_size, stat.st_mtime_ns]
    # Auto retains existing usable fragments. Forced CPU has its own cache so
    # the override can bypass a fragment generated by a troublesome GPU driver.
    if acceleration == "cpu":
        key.append("cpu")
    return hashlib.sha256(json.dumps(key).encode()).hexdigest()


def manifest(path, info, acceleration="auto"):
    audio = bool(info["has_audio"])
    return {"version": VERSION, "source_key": source_key(path, acceleration), "duration": info["duration"],
            "acceleration": acceleration,
            "chunk_seconds": CHUNK_SECONDS, "chunks": math.ceil(info["duration"] / CHUNK_SECONDS),
            "height_limit": 480, "fps": 30, "has_audio": audio,
            "mime": 'video/mp4; codecs="avc1.42c01f' + (', mp4a.40.2"' if audio else '"')}


def prune(cache):
    """Bound the preview-only cache, never touching originals or audio fingerprints."""
    global _last_cleanup
    if time.monotonic() - _last_cleanup < 60 or not _CLEANUP_LOCK.acquire(blocking=False):
        return
    try:
        _last_cleanup = time.monotonic()
        files = sorted(cache.glob("*/*.mp4"), key=lambda p: p.stat().st_mtime)
        total = sum(p.stat().st_size for p in files)
        for path in files:
            if total <= CACHE_LIMIT:
                break
            # Recently requested/current chunks remain available to FileResponse.
            if time.time() - path.stat().st_mtime < 120:
                continue
            size = path.stat().st_size
            path.unlink(missing_ok=True)
            path.with_suffix(".json").unlink(missing_ok=True)
            total -= size
    finally:
        _CLEANUP_LOCK.release()


def fragment(path, info, index, cache, execute, process_key, cancelled, acceleration="auto"):
    path, cache = Path(path), Path(cache)
    descriptor = manifest(path, info, acceleration)
    if index < 0 or index >= descriptor["chunks"]:
        raise ValueError("Preview chunk is outside this recording")
    source_id = descriptor["source_key"]
    output = cache / source_id / f"{index:06d}.mp4"
    metadata = output.with_suffix(".json")
    lock = _LOCKS[int(source_id[:8], 16) % len(_LOCKS)]
    while not lock.acquire(timeout=.25):
        if cancelled.is_set():
            raise RuntimeError("Preview request cancelled")
    try:
        if cancelled.is_set():
            raise RuntimeError("Preview request cancelled")
        if output.is_file() and metadata.is_file():
            try:
                details = json.loads(metadata.read_text())
                if not all(math.isfinite(float(details[k])) for k in ("start", "duration", "video_start")):
                    raise ValueError("Invalid cached preview timing")
                os.utime(output, None)
                return output, details
            except (ValueError, KeyError):
                metadata.unlink(missing_ok=True)
        output.parent.mkdir(parents=True, exist_ok=True)
        start = index * CHUNK_SECONDS
        duration = min(CHUNK_SECONDS, info["duration"] - start)
        scale = min(1, 854 / info["width"], 480 / info["height"])
        width, height = [max(2, int(v * scale / 2) * 2) for v in (info["width"], info["height"])]
        temporary = output.with_suffix(".partial.mp4")
        clip_format = (info.get("codec"), info.get("pixel_format"), info.get("rotation", 0), info["width"], info["height"])
        candidates = hardware_decoders() if acceleration == "auto" else ()
        with _GPU_LOCK:
            methods = [candidate for candidate in candidates if candidate + clip_format not in _HARDWARE_DISABLED]
        methods.append(("cpu", None, False))
        decoder = "cpu"
        for method, device, gpu_scale in methods:
            if cancelled.is_set():
                raise RuntimeError("Preview request cancelled")
            command = [shutil.which("ffmpeg") or "ffmpeg", "-nostdin", "-y", "-v", "error", "-threads", "2"]
            if method != "cpu":
                command += ["-hwaccel", method]
                if device is not None:
                    command += ["-hwaccel_device", device]
                if method in {"cuda", "vaapi", "d3d11va"}:
                    command += ["-hwaccel_output_format", "d3d11" if method == "d3d11va" else method]
            command += ["-ss", f"{start:.9f}", "-i", str(path), "-map", "0:v:0", "-map", "0:a:0?", "-sn", "-dn", "-filter_threads", "1"]
            if method in {"cuda", "vaapi", "d3d11va"}:
                downloaded = "p010le" if "10" in (info.get("pixel_format") or "") else "nv12"
                if gpu_scale and method == "cuda":
                    filters = f"scale_cuda={width}:{height}:interp_algo=bilinear,hwdownload,format={downloaded},format=yuv420p"
                elif gpu_scale and method == "vaapi":
                    filters = f"scale_vaapi=w={width}:h={height}:format=nv12,hwdownload,format=nv12,format=yuv420p"
                else:
                    filters = f"hwdownload,format={downloaded},scale={width}:{height}:flags=fast_bilinear,format=yuv420p"
            else:
                filters = f"scale={width}:{height}:flags=fast_bilinear,format=yuv420p"
            command += ["-vf", filters + ",setsar=1,setpts=PTS-STARTPTS,fps=30:start_time=0",
                        "-af", "asetpts=PTS-STARTPTS,aresample=48000:async=1:first_pts=0,apad",
                        "-t", f"{duration:.9f}", "-c:v", "libx264", "-preset", "ultrafast", "-tune", "zerolatency",
                        "-crf", "27", "-profile:v", "baseline", "-level:v", "3.1", "-pix_fmt", "yuv420p",
                        "-g", "30", "-keyint_min", "30", "-sc_threshold", "0", "-bf", "0", "-threads", "2",
                        "-c:a", "aac", "-b:a", "96k", "-ar", "48000", "-ac", "2",
                        "-avoid_negative_ts", "make_zero", "-movflags", "+frag_keyframe+empty_moov+default_base_moof",
                        "-f", "mp4", str(temporary)]
            try:
                execute(process_key, command, output.with_suffix(".log"), timeout=120 if method == "cpu" else 30)
                decoder = method
                break
            except RuntimeError:
                if method == "cpu" or cancelled.is_set():
                    raise
                with _GPU_LOCK:
                    _HARDWARE_DISABLED.add((method, device, gpu_scale) + clip_format)
        if cancelled.is_set() or source_key(path, acceleration) != source_id:
            raise RuntimeError("Preview cancelled or source recording changed; reload the video")
        # fMP4 muxing may shift video by AAC encoder priming. Report the actual
        # first video timestamp so MSE can place every frame on the source clock.
        probe = subprocess.run([shutil.which("ffprobe") or "ffprobe", "-v", "error", "-select_streams", "v:0",
                                "-show_entries", "stream=start_time", "-of", "json", str(temporary)],
                               capture_output=True, text=True, timeout=10, check=True)
        video_start = float(json.loads(probe.stdout)["streams"][0].get("start_time", 0))
        if not math.isfinite(video_start):
            raise ValueError("Preview fragment has invalid timing")
        details = {"start": start, "duration": duration, "video_start": video_start, "decoder": decoder}
        os.replace(temporary, output)
        metadata.write_text(json.dumps(details), encoding="utf-8")
        # Logs contain no useful cache data after successful encoding.
        output.with_suffix(".log").unlink(missing_ok=True)
        prune(cache)
        return output, details
    finally:
        output.with_suffix(".partial.mp4").unlink(missing_ok=True)
        lock.release()
